authentication/urls.py
from django.urls import path

from . import views


app_name = 'authentication'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.signin, name='signin'),
    path('logout/', views.sign_out, name='sign_out')
]

college_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls")),
    path("auth/", include("authentication.urls")),
    path("order/", include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views


app_name = 'order'

urlpatterns = [
    path('home/<username>/', views.order_home, name='order_home'),
    path('form/', views.order_form, name='order_form'),

    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),  # AJAX
]

website/urls.py
from django.urls import path

from . import views


app_name = 'website'

urlpatterns = [
    path('', views.home, name='home')
]

authentication/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=100, unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


PURPOSES = (
    ('enquiry', 'Enquiry'),
    ('place_order', 'Place Order'),
    ('return', 'Return')
)


class Order(models.Model):
    name = models.CharField(max_length=250)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    phone = models.CharField(max_length=10)
    mail = models.EmailField()
    address = models.TextField(blank=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    purpose = models.CharField(max_length=100, choices=PURPOSES, default='place_order')
    material = models.CharField(max_length=100)

    def __str__(self):
        return self.name

website/models.py
from django.db import models

# Create your models here.

order/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple
from django.contrib.admin.widgets import AdminDateWidget

from .models import Order, Course


class DatePickerInput(forms.DateInput):
    input_type = 'date'

class OrderForm(forms.ModelForm):
    MATERIALS = (
    ('note_book', 'Note Book'),('pencil', 'Pencil'),('pen', 'Pen'),
    ('scale', 'Scale'),
    ('box', 'Box'),
    ('exam_paper', 'Exam Paper')
    )
    dob = forms.DateField(widget=DatePickerInput)
    material = forms.MultipleChoiceField(choices=MATERIALS, widget=CheckboxSelectMultiple)

    class Meta:
        model = Order
        fields = "name", "dob", "age", "gender", "phone", "mail", "address", "department", "course", "purpose", "material"
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

authentication/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        re_password = request.POST['re_password']

        if password == re_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, "Username Already Taken")
                return redirect('authentication:register')
            elif User.objects.filter(email=email).exists():
                messages.error(request, "Email Already In Use")
                return redirect('authentication:register')
            else:
                new_user = User.objects.create_user(username, email, password)
                new_user.save()
                messages.success(request, "Your account has been successfully created.")

                return redirect('authentication:signin')
                
        else:
            messages.error(request, "Passwords don't match!")
            return redirect('authentication:register')

    return render(request, 'authentication/register.html')


def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('order:order_home', username)
        else:
            messages.error(request, "Bad Credentials!")
            return redirect('authentication:signin')

    return render(request, 'authentication/login.html')


def sign_out(request):
    logout(request)
    return redirect('website:home')

order/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import OrderForm
from .models import Course


@login_required
def order_home(request, username):
    return render(request, 'order/order_home.html', {'username': username})


@login_required
def order_form(request):
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your Order Has Been Placed")
            return redirect('order:order_form')
        else:
            messages.error(request, "Couldn't Place the Order")
            return redirect('order:order_form')
    return render(request, 'order/order_form.html', {'form': form})


def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id)
    return render(request, 'order/course_dropdown_list_options.html', {'courses': courses})

website/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'website/index.html')

templates/authentication/login.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} LogIn {% endblock %}


{% block body %}

<div class="login-form">

    <form action="" method="POST">
        <h2>LOG IN</h2>

        {% for message in messages %}
        <div class="messages" style="font-size: 1.5rem;">
            {{ message }}
        </div>
        {% endfor %}

        {% csrf_token %}

        <label class="form-label">Username</label>
        <input class="form-control" type="text" name="username" placeholder="Enter your Username" required>
        <br>
        <label class="form-label">Password</label>
        <input class="form-control" type="password" name="password" placeholder="Enter password" required>
        <br>
        <div class="d-grid">
            <button class="btn btn-primary" type="submit">SignIn</button>
        </div>
    </form>

</div>

{% endblock %}

templates/authentication/register.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Register {% endblock %}


{% block body %}

<div class="register-form">

    <form action="" method="POST">
        <div class="heading">
            <h2>Register</h2>
        </div>
        {% for message in messages %}
        <div class="messages">
            <h4 style="color: red; font-size: 1.5rem;">{{ message }}</h4>
        </div>
        {% endfor %}
        {% csrf_token %}

        <label class="form-label">Username</label>
        <input class="form-control" type="text" name="username" placeholder="Type a Username (Only letters and numbers)"
            required>
        <br>
        <label class="form-label">Email</label>
        <input class="form-control" type="email" name="email" placeholder="Enter your email" required>
        <br>
        <label class="form-label">Password</label>
        <input class="form-control" type="password" name="password" placeholder="Enter password" required>
        <br>
        <label class="form-label">Confirm Password</label>
        <input class="form-control" type="password" name="re_password" placeholder="Confirm password" required>
        <br>
        <div class="d-grid">
            <button class="btn btn-primary" type="submit">SignUp</button>
        </div>
    </form>

</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href=" {% static 'css/styles.css' %}" rel="stylesheet">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    
{% include 'header.html' %}

{% block body %}
{% endblock %}


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

templates/header.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'website:home' %}">C-Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Department
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Biology"
                                target="_blank">Biology Science</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science"
                                target="_blank">Computer Science</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce"
                                target="_blank">Commerce</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Electronics"
                                target="_blank">Electronics</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities"
                                target="_blank">Humanities</a>
                        </li>
                    </ul>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'authentication:sign_out' %}">LogOut</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'authentication:signin' %}">LogIn</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                        href="{% url 'authentication:register' %}">Register</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

templates/order/course_dropdown_list_options.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

templates/order/order_form.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Order {% endblock %}


{% block body %}

<div class="container-fluid order-form">

    <div>

        <form action="" method="POST" id="orderForm" data-courses-url="{% url 'order:ajax_load_courses' %}">
            <div class="order-page">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <div class="d-grid gap-2">
                    <button class="btn btn-primary" type="submit">Submit</button>
                    <a href="{% url 'authentication:sign_out' %}" class="btn btn-danger">LogOut</a>
                </div>
            </div>
        </form>

    </div>

</div>

{% if messages %}
{% for message in messages %}
<div class="container-fluid shadow order-home">
    <div class="row">
        <div class="col-md-12">
            <div class="messages">
                {{ message }}
            </div>
            {% endfor %}
            <div class="order-summery">
                <a href="{% url 'website:home' %}">Return to Home</a><br>
                <a href="{% url 'order:order_form' %}">Order Again</a>
            </div>

        </div>
    </div>
</div>
{% endif %}


<!---JQuery--->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>

    $("#id_department").change(function () {
        const url = $("#orderForm").attr("data-courses-url");  // get the url of the `load_courses` view
        const departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-courses/ )
            data: {
                'department_id': departmentId       // add the department id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_courses` view function
                $("#id_course").html(data);  // replace the contents of the course input with the data that came from the server

            }
        });

    });

</script>

{% endblock %}

templates/order/order_home.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Welcome {{ username }} {% endblock %}


{% block body %}

<div class="container-fluid shadow order-home">

    <div class="row">
        <div class="col-md-12">

            <div class="card-body">
                <h2>WELCOME <span class="username">{{ username }}</span></h2>

                <a href="{% url 'order:order_form' %}" class="btn btn-secondary btn-lg">Click Here To Order</a>
            </div>

        </div>
    </div>

</div>

{% endblock %}

templates/website/index.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} College Store {% endblock %}


{% block body %}

<div class="container-fluid home-card">

    <div class="row">

        <div class="shadow col-md-12">
            <div class="card-body">
                <h1>WELCOME</h1>
                {% if user.is_authenticated %}
                <div>
                    <a href="{% url 'order:order_form' %}" class="btn btn-secondary btn-lg">Click Here To Order</a>
                </div>
                {% else %}
                <div>
                    <a href="{% url 'authentication:register' %}" class="btn btn-outline-primary">Register</a>
                    <a href="{% url 'authentication:signin' %}" class="btn btn-outline-success">LogIn</a>
                </div>
                {% endif %}
            </div>
        </div>

    </div>

</div>

{% endblock %}